exemploasp/Controllers/ExposicaoController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Resources;
using System.Security.Cryptography.Pkcs;
using System.Web;
using System.Web.Mvc;
using exemploasp.InteractDB;
using exemploasp.Models;
using exemploasp.Patterns;
using exemploasp.Patterns.TemplateMethod;
using exemploasp.ViewModels;
using Exposicao = exemploasp.Models.Exposicao;

namespace exemploasp.Controllers
{
    public class ExposicaoController : Controller
    {
        OurDBContext db = new OurDBContext();
		MuseuInteractDb museuDB = new MuseuInteractDb();

        // GET: Exposicao
        //Lista de todas as exposições
        [Authorize(Users = "Administrador")]
		public ActionResult Index()
        {
	            if (TempData["Message"] != null) ViewBag.Message = TempData["Message"].ToString();
                return View(db.Exposicao.ToList());
        }

		//Lista exposições de acordo com o user
	    [Authorize]
		public ActionResult Lista()
        {
            int id = Convert.ToInt32(Session["UserAccountID"]);
            UserAccount userAccount = db.UserAccount.Where(u => u.UserAccountID == id).Include(u => u.Temas).Include(u => u.UserAccountExposicaos).SingleOrDefault();
            ViewBag.UserAccount = userAccount;
            return View(db.Exposicao.Include(e => e.Temas).OrderByDescending(e => e.ExposicaoID).ToList());
        }

		// GET: Exposicao/Create
	    [Authorize(Users = "Administrador")]
		public ActionResult Create()
        {
            var exposicao = new Exposicao();
            exposicao.Temas = new List<Tema>();
            ViewBag.Temas = museuDB.PopulateAssignedTemaData(exposicao);
            return View();
        }

		// POST: Exposicao/Create
        //verifica se os dados introduzidos são válidos e de seguida salva em bd.exposicao a nova exposição.É utilizado o template method
		[Authorize(Users = "Administrador")]
		[HttpPost]
        public ActionResult Create([Bind(Include = "Nome,DataInicial,DataFinal,Duracao,NrItens")]Exposicao exposicao, string[] selectedTemas)
        {
	        if (ModelState.IsValid)
	        {
                ObjetoMuseu oExposicao = new ObjExposicao(exposicao);
	            if (oExposicao.Validar() == null)
	            {
	                oExposicao.SalvarBd(db);
	                var exposicaoUpdate = db.Exposicao.Include(t => t.Temas).Single(e => e.ExposicaoID == exposicao.ExposicaoID);
                    museuDB.UpdateTemas(selectedTemas, exposicaoUpdate, db);
                }
	            else
	            {
	                exposicao.Temas = new List<Tema>();
	                ViewBag.Temas = museuDB.PopulateAssignedTemaData(exposicao);
	                ModelState.AddModelError("", oExposicao.Validar());
	                return View();

                }
	            ModelState.Clear();
	            TempData["Message"] = exposicao.Nome + " adicionado com sucesso"; 
            }
            return RedirectToAction("Index");
        }

        //manda para a view os dados necessários para editar a exposição selecionada
		[Authorize(Users = "Administrador")]
		public ActionResult Edit(int? id)
	    {
		    Exposicao exposicao = db.Exposicao.Include(t => t.Temas).SingleOrDefault(u => u.ExposicaoID == id);
		    if (exposicao == null || id == null)
		    {
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}
	        ViewBag.Temas = museuDB.PopulateAssignedTemaData(exposicao);
            return View(exposicao);
	    }

        //atualiza os dados da exposição selecionada
		[Authorize(Users = "Administrador")]
		[HttpPost]
		public ActionResult Edit(int? id,string Nome, DateTime DataInicial, DateTime DataFinal, DateTime Duracao, int NrItens, string[] selectedTemas)
	    {
			if (id == null)
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
	        var exposicaoUpdate = db.Exposicao.Include(t => t.Temas).Single(e => e.ExposicaoID == id);
            if (TryUpdateModel(exposicaoUpdate, "",
			    new string[] {"Nome,DataInicial,DataFinal,Duracao,NrItens"}))
		    {
			    try
			    {
			        exposicaoUpdate.Nome = Nome;
			        exposicaoUpdate.DataInicial = DataInicial;
			        exposicaoUpdate.DataFinal = DataFinal;
			        exposicaoUpdate.Duracao = Duracao;
			        exposicaoUpdate.NrItens = NrItens;
				    museuDB.UpdateTemas(selectedTemas, exposicaoUpdate, db);
				    return RedirectToAction("Index");
			    }
			    catch (RetryLimitExceededException /* dex */)
			    {
				    ModelState.AddModelError("", "Nao foi possivel atualizar a exposição");
			    }
			}
            return View(exposicaoUpdate);
	    }

        //remove a exposição selecionada
	    [Authorize(Users="Administrador")]
		public ActionResult Delete(int? id)
	    {
		    var exposicaoToDelete = db.Exposicao.SingleOrDefault(e => e.ExposicaoID == id);
		    if (exposicaoToDelete != null)
		    {
			    db.Exposicao.Remove(exposicaoToDelete);
			    db.SaveChanges();
			    TempData["Message"] = exposicaoToDelete.Nome + " removido com sucesso";
			}
		    else
		    {
			    TempData["Message"] = "Erro ao remover Exposição";
		    }
		    return RedirectToAction("Index");
		}

        //envia para a view todas as exposições que já terminaram
        public ActionResult Arquivo()
        {
            List<Exposicao> exposicoes = db.Exposicao.Where(e => e.DataFinal < DateTime.Today).ToList();
            return View(exposicoes);
        }
    }
}

exemploasp/Controllers/TemaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using exemploasp.Models;
using System.Data.Entity;
using System.Web.Services.Description;
using exemploasp.Patterns.TemplateMethod;

namespace exemploasp.Controllers
{
    public class TemaController : Controller
    {
        private OurDBContext db = new OurDBContext();

		// GET: Tema
	    [Authorize(Users = "Administrador")]
		public ActionResult Index()
        {
            using (OurDBContext db = new OurDBContext())
            {
                if (TempData["Message"] != null) ViewBag.Message = TempData["Message"].ToString();
                return View(db.Tema.ToList());
            }
        }

		// GET: Tema/Create
	    [Authorize(Users = "Administrador")]
		public ActionResult Create()
        {
            return View();
        }

		// POST: Tema/Create
	    [Authorize(Users = "Administrador")]
		[HttpPost]
        public ActionResult Create(Tema tema)
        {
            ObjetoMuseu oTema = new ObjTema(tema);
            if (ModelState.IsValid)
            {
                if (oTema.Validar() == null)
                {
                    oTema.SalvarBd(db);
                    TempData["Message"] = tema.Nome + " criado com sucesso";
                }
                else
                {
                    TempData["Message"] = oTema.Validar();
                }
            }
            ModelState.Clear();
	        return RedirectToAction("Index");          
        }

		// GET: Tema/Delete/5
	    [Authorize(Users = "Administrador")]
		public ActionResult Delete(int? id)
          {
              var temaToDelete = db.Tema.SingleOrDefault(t => t.TemaID == id);
              if (temaToDelete != null)
              {
                  db.Tema.Remove(temaToDelete);
                  db.SaveChanges();
                  TempData["Message"] = temaToDelete.Nome + " removido com sucesso";
              }
              else
              {
                  TempData["Message"] = "erro ao remover o tema";
              }
              return RedirectToAction("Index");
        }
    }
}

exemploasp/Views/Shared/_Layout.cshtml
@using System.Web.Mvc.Html
@using exemploasp.Controllers
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/Content/css/teste.css" media="screen" type="text/css" />
    <title>@ViewBag.Title - Guider Management</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    
    
    <!--  FOOTER -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="/Content/css/Footer-with-social-icons.css">
    

</head>
<body>
 
        @{
        if (Session["UserAccountId"] != null)
        {
            <div class="navbar navbar-inverse navbar-fixed-top">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>

                        <a class="navbar-brand" rel="home" href="/Home/Index" title="Buy Sell Rent Everyting">
                            <img style="max-width: 80px; margin-top: -10px;"
                                 src="/Content/images/logo_nav.png">
                        </a>



                    </div>
                    <div class="navbar-collapse collapse">
                        <ul class="nav navbar-nav">
                            <li>@Html.ActionLink("Candidaturas", "Candidatura", "UserAccountExposicao")</li>
                            <li>@Html.ActionLink("Exposições", "Lista", "Exposicao")</li>
                            @{
                            if ((string)Session["TipoUtilizador"] == "Administrador")
                            {
                                <li class="dropdown">
                                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                        Gestão Do Museu
                                        <span class="caret"></span>
                                    </a>
                                    <ul class="dropdown-menu">
                                        <li>@Html.ActionLink("Temas", "Index", "Tema")</li>
                                        <li>@Html.ActionLink("Exposições", "Index", "Exposicao")</li>
                                        <li>@Html.ActionLink("Marcações", "Index", "Marcacao")</li>
                                        <li>@Html.ActionLink("Utilizadores", "Index", "Account")</li>
                                        <li>@Html.ActionLink("Candidaturas", "GestaoCandidaturas", "UserAccountExposicao")</li>
                                    </ul>
                                </li>
                        }
                            }
                        </ul>


                        <ul class="nav navbar-nav navbar-right">
                            <li class="dropdown">
                                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                    @Session["Username"]
                                    <span class="caret dropdown-toggle"></span>
                                </a>

                                <ul class="dropdown-menu">
                                    
                                
                                    <li>@Html.ActionLink("Conta de Utilizador", "PerfilUser", "Account")</li>
                                    <li>@Html.ActionLink("Editar Perfil", "Edit", "Account")</li>
                                    <li>&nbsp;</li>
                                    <li>@Html.ActionLink("Logout", "Logout", "Account")</li>
                                </ul>

                            </li>
                        </ul>


                    </div>
                </div>
            </div>
    }
        }

            @RenderBody()
            @if (Session["UserAccountId"] != null)
        {

            <footer id="myFooter">
                <div class="container">
                    <div class="row">
                        <div class="col-sm-4 myCols">
                            <h5>Sobre</h5>
                            <br/>
                            <ul>
                                <li align ="justify">
                                    A Quinta das Cruzes é uma das quintas com maior tradição histórica do Funchal, 
                                    ligada à família dos primeiros capitães donatários, 
                                    uma vez que foi nestas imediações que a mesma estabeleceu a sua segunda residência. 
                                    Permaneceu na família Câmara até meados do século XVII, 
                                    transitando para a família Lomelino até finais do século XIX.
  
                                </li>
                            </ul>
                        </div>
                        <div class="col-sm-4 myCols">
                            <h5>Localização</h5>
                            <br/>
                            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2786.306355986235!2d-16.915955985428713!3d32.65107369770482!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0xc605fe23cfcb4c7%3A0x734b5f191feed738!2sMuseu+da+Quinta+das+Cruzes!5e1!3m2!1spt-PT!2spt!4v1517929231700" sytle="" frameborder="0" style="border:0" allowfullscreen></iframe>
                        </div>
                        <div class="col-sm-4 myCols">
                            <h5>Contatos</h5>
                            <br/>
                            <ul>
                                <li><b><u><i class="glyphicon glyphicon-earphone"></i></u></b> 291 740 670</li>
                                <li><b><u><i class="glyphicon glyphicon-envelope"></i></u></b> quintadascruzes.suporte@gmail.com</li>
                            </ul>
                            <br />
                            <ul>
                                <li>
                                    <b><i class="glyphicon glyphicon-time"></i></b>
                                    Terça-feira a Domingo 
                                </li>
                                <li>10:00 - 12:30 e das 14:00 -17:30</li>

                            </ul>
                        </div>


                     
                    </div>
                </div>
                <div class="social-networks">
                    <a href="#" class="twitter"><i class="fa fa-twitter"></i></a>
                    <a href="#" class="facebook"><i class="fa fa-facebook-official"></i></a>
                    <a href="#" class="google"><i class="fa fa-google-plus"></i></a>
                </div>
                
                
                <div class="footer-copyright">
                    <p>&copy; @DateTime.Now.Year - Guider Management</p>
                </div>
            </footer>

    }


        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)

</body>


</html>