exemploasp/Models/TipoUtilizador.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IdentityModel.Policy;
using System.Linq;
using System.Web;

namespace exemploasp.Models
{
	public class TipoUtilizador
	{
		[Key]
		public int TipoUtilizadorID { get; set; }

		[Display(Name = "Tipo de utilizador")]
		[Required(ErrorMessage = "Introduza um tipo de utilizador")]
		public string Tipo { get; set; }

		public virtual ICollection<UserAccount> UserAccounts { get; set; }
	}
}

exemploasp/Controllers/TipoUtilizadorController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using exemploasp.Models;

namespace exemploasp.Controllers
{
	public class TipoUtilizadorController : Controller
	{

		OurDBContext db = new OurDBContext();

		// GET: TipoUtilizador
		[Authorize(Users = "Administrador")]
		public ActionResult Index()
		{
			using (OurDBContext db = new OurDBContext())
			{
				if (TempData["Message"] != null) ViewBag.Message = TempData["Message"].ToString();
				return View(db.TipoUtilizador.ToList());
			}
		}


		// GET: TipoUtilizador/Create
		[Authorize(Users = "Administrador")]
		public ActionResult Create()
		{
			
			return View();
		}



		// POST: TipoUtilizador/Create

		[Authorize(Users = "Administrador")]
		[HttpPost]
		public ActionResult Create(TipoUtilizador tipoUtilizador)
		{
			try
			{
				if (!db.TipoUtilizador.Any(n => n.Tipo == tipoUtilizador.Tipo))
				{
						db.TipoUtilizador.Add(tipoUtilizador);
						db.SaveChanges();
				}
					
				ModelState.Clear();


				return RedirectToAction("Index");
			}
			catch
			{
				return View();
			}
		}

		// GET: TipoUtilizador/Delete/5
		[Authorize(Users = "Administrador")]
		public ActionResult Delete(int? id)
        {

	        TipoUtilizador tipoUtilizador = db.TipoUtilizador.Find(id);
			if (tipoUtilizador != null)
	        {
				db.TipoUtilizador.Remove(tipoUtilizador);
				db.SaveChanges();
		        TempData["Message"] = tipoUtilizador.Tipo + " removido com sucesso";
			}
			else
			{
				TempData["Message"] = "erro ao remover o tipo de utilizador";
			}

	        return RedirectToAction("Index");
        }

    }
}

exemploasp/Views/TipoUtilizador/Create.cshtml
@model exemploasp.Models.TipoUtilizador

@{
    ViewBag.Title = "Create";
}

<div class="container">
<div class="row">

    <h2>Adicionar um novo tipo de utilizador</h2>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">

            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Tipo, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Tipo, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Tipo, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Adicionar" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Voltar atrás", "Index")
    </div>
    <br/>
    
</div>
</div>

exemploasp/Views/TipoUtilizador/Funcao.cshtml
@{
    ViewBag.Title = "Funcao";
}

<h2>Adicionar Função a Utilizador</h2>
<hr>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">


        <div class="form-group">

            <label class="control-label col-md-2" for="UserAccountID">Utilizador</label>
            <div class="col-md-10">
                @Html.DropDownList("UserAccountID", "--Selecionar--")
            </div>

        </div>
        
        
        <div class="form-group">

            <label class="control-label col-md-2" for="TipoUtilizadorID">Função</label>
            <div class="col-md-10">
                @Html.DropDownList("TipoUtilizadorID", "--Selecionar--")
            </div>

        </div>
        
        
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Definir função" class="btn btn-default" />
            </div>
        </div>
        

    </div>
}

exemploasp/Views/TipoUtilizador/Index.cshtml
@model IEnumerable<exemploasp.Models.TipoUtilizador>

@{
    ViewBag.Title = "Gestão de Utilizadores";
}

<link rel="stylesheet" href="/Content/css/app.css" media="screen" type="text/css" />
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script src="http://getbootstrap.com/dist/js/bootstrap.min.js"></script>

<div class="container">
    <div class="row">
    <h2>Gestão de Utilizadores</h2>
    <hr />




    <a href="@Url.Action("Create", "TipoUtilizador")" class="btn btn-success btn-md">
        <span class="glyphicon glyphicon-plus"></span> Adicionar Função
    </a>
    <a href="@Url.Action("Funcao", "Account")" class="btn btn-warning btn-md">
        <span class="glyphicon glyphicon-edit"></span> Alterar Função de um utilizador
    </a>
    <h4 class="message">@ViewBag.Message</h4>

 

        @{
            if (Model.Any())
            {


                <div class="col-md-12">
                    <div class="table-responsive">
                        <table id="mytable" class="table table-bordred table-striped">

                            <tr>


                                <th>@Html.DisplayNameFor(model => model.Tipo)</th>
                                <th>Eliminar</th>

                            </tr>



                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@Html.DisplayFor(modelItem => item.Tipo)</td>
                                    <td>
                                        <p data-placement="top" data-toggle="tooltip" title="Eliminar">
                                            <a onclick="say_hi(@item.TipoUtilizadorID)" href="#" class="btn btn-danger btn-sm"> <span class="glyphicon glyphicon-trash"> </span> </a>
                                        </p>
                                    </td>
                                </tr>

                            }
                        </table>

                    </div>
                </div>
            }
            else
            {
                <h1>Ainda não existem Tipos de Utilizador.</h1>
                <h4><a href="@Url.Action("Create", "TipoUtilizador")">Adicionar Novo Tipo de Utilizador</a></h4>
            }
        }

        <script type="text/javaScript">
            function say_hi(idt) {
                var hi = confirm("Quer mesmo apagar este tema?");
                if (hi == true) {
                    window.location.href = "/TipoUtilizador/Delete/" + idt;
                }
            }
        </script>
    </div>


</div>